apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    run: web-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: accounts-port
    protocol: TCP
  selector:
    app: accountsapi